### PR TITLE
Feature/sticky navbar

### PR DESCRIPTION
**Pull request by Bluesmile82**
- Fix the navbar by default
- Use the transparent theme until we scroll
- Also fix the second navbar below the first one

I included a dummy element on the ThemeNavbar to avoid jumps and adding paddings on the main

### CODE REVIEW

**Review by tsubik — CHANGES_REQUESTED** [review]
On the map page the header was ok and shouldn't be changed as there will not be any scrolling.

**Comment by Bluesmile82** [comment]
Thanks! I adapted the rest of the map page. I think the header should stay like that for consistency. Please let me know if you disagree

**Comment by tsubik** [comment]
The rest of pages looks very nice, but still on map page the header was by design different, full-width, and there should be no scrolling. I would revert to this https://tota.vercel.app/map.

**Review by tsubik — APPROVED** [review]
Looks great!

**Pull request merged**
